# Generated by Django 5.0 on 2023-12-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("street_line_1", models.CharField(max_length=255)),
                ("street_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=80)),
                ("state", models.CharField(max_length=80)),
                ("zip_code", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
    ]
